name: Build Flutter macOS App

on:
  push:
    branches: [main]  # 触发分支
  pull_request:
    branches: [main]
  workflow_dispatch:  # 支持手动触发

jobs:
  build:
    runs-on: macos-latest  # 必须使用 macOS 环境
    steps:
      - uses: actions/checkout@v4  # 拉取代码
      
      - uses: subosito/flutter-action@v2.14.0
        with:
          # The Flutter version to make available on the path
          flutter-version: any # optional, default is any
          # The Flutter build release channel
          channel: stable # optional, default is stable
          # Cache the Flutter SDK
          cache: false # optional, default is false
          # Identifier for the Flutter SDK cache
          # cache-key: # optional, default is flutter-:os:-:channel:-:version:-:arch:-:hash:
          # Identifier for the Dart .pub-cache cache
          # pub-cache-key: # optional, default is flutter-pub:os:-:channel:-:version:-:arch:-:hash:
          # Flutter SDK cache path
          # cache-path: # optional, default is ${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:
          # Flutter pub cache path
          # pub-cache-path: # optional, default is default
          # The architecture of Flutter SDK executable (x64 or arm64)
          # architecture: # optional, default is ${{ runner.arch }}
                
      - run: flutter pub get  # 获取依赖
      
      - run: flutter build macos --release  # 构建 macOS 应用
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-App
          path: build/macos/Build/Products/Release/  # 构建产物路径
